name: Deploy to AWS
on:
  push:
    branches:
      - 'master'

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: 'npm'
          cache-dependency-path: ./

      - name: Install serverless globally
        run: npm i serverless -g

      - name: Config deploy credentials
        run: | 
            serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID  --secret $AWS_SECRET_ACCESS_KEY
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run deploy
        run: npm run deploy